### ISSUE TITLE
Дока

### ISSUE THREAD

**Issue by Barmunksu** [agentsib/diadoc-php#1]
Можете составить пример подключения с одним запросом?

**Comment by agentsib** [comment]
Вот пример. Надо будет действительно добавить примеры...

```php
<?php

require __DIR__.'/vendor/autoload.php';

$ddAuth = 'developer.key-1234123-123412-43232-1234142-38a12342321';
$signerCloud = new \AgentSIB\Diadoc\Model\CloudOpensslSignerProvider('http://localhost:8888/', 'SecretToken');

$client = new \AgentSIB\Diadoc\DiadocApi($ddAuth, $signerCloud);

$client->authenticateLogin('login', 'password'); // By Login
//$client->authenticateCertificate($certFile); // By Certificate

// Работа с организацией
$organization = new \AgentSIB\Diadoc\OrganizationApi($client, 'Orginization ID');

// Работа с ящиком
$box = new \AgentSIB\Diadoc\BoxApi($client, 'BOXID@diadoc.ru');


/// Пример отправки внутреннего подписанного документа
$now = new \DateTime();
$message = new \AgentSIB\Diadoc\Api\Proto\Events\MessageToPost();

// Создание неформализованного документа
$attachment = new \AgentSIB\Diadoc\Api\Proto\Events\NonformalizedAttachment();
$content = $client->generateSignedContentFromFile(__DIR__.'/composer.json');
$attachment->setSignedContent($content);
$attachment->setComment('Комментарий');
$attachment->setFileName('Filename.json');
$attachment->setDocumentDate($now->format('d.m.Y'));
$attachment->setDocumentNumber(1);
$message->addNonformalizedDocuments($attachment);

$message->setFromBoxId($box->getBox()->getBoxId());
$message->setFromDepartmentId('DEPARTMENT_FROM_ID');
$message->setToDepartmentId('DEPARTMENT_TO');
//$message->setIsDraft(true);
$message->setIsInternal(true);

// Публикация сообщения
echo $response = $client->postMessage($message);
```

**Comment by Bezarama** [comment]
Добрый день.
Скажите, пожалуйста, PHP расширение php-protobuf требуется для нормальной работы?
Спасибо.

**Comment by agentsib** [comment]
@Bezarama Добрый день. Не требуется. Используется https://github.com/protobuf-php/protobuf для работы с protobuf. Библиотека включена в зависимость.

**Comment by Bezarama** [comment]
Спасибо за ответ.
Дело в том, что, мне предстоит делать интеграцию с диадоком без использования фреймворка (ларавел, симфони и т.д.). Я могу как-то использовать Ваш труд в таком случае?
Т.е. Ваш API и  https://github.com/protobuf-php/protobuf есть возможность подключить и использовать без кровавых костылей?

**Comment by agentsib** [comment]
@Bezarama Библиотека лежит на github под лицензией MIT, так что ограничений по любому использованию нет) 
Сама по себе библиотека не тянет зависимости фреймворков. Ставьте через композер, зависимости подтянутся автоматически. Пример использования выше.

**Comment by Bezarama** [comment]
Большое спасибо!

С уважением,
Денис

**Comment by SviatoslavBereznitskyi** [comment]
Здравствуйте, скажыте, пожалуйста, можна ли с помощью Вашой библиотеки скачивать документы с  внутрениго ящика, если да можна какой-то пример?
Спасибо

**Comment by agentsib** [comment]
@SviatoslavBereznitskyi 
Добрый день

https://github.com/agentsib/diadoc-php/blob/master/src/BoxApi.php#L90
https://github.com/agentsib/diadoc-php/blob/master/src/DiadocApi.php#L673

Документация: http://api-docs.diadoc.ru/ru/latest/http/GetEntityContent.html

**Comment by SviatoslavBereznitskyi** [comment]
Здравствуйте.
Здесь первым параметром должен быть URL своего сайта? И что такое SecretToken?  ` $signerCloud = new CloudOpensslSignerProvider('http://localhost:8888/', 'SecretToken');`
Спасибо!

**Comment by agentsib** [comment]
Добрый день. Нет, это url от этого проекта:  https://github.com/agentsib/diadoc-cloud-signer

Это в случае, если вы не можете использовать openssl с ГОСТом на веб сервере.

Вообще проект надо давно обновить...

**Comment by ethaniel** [comment]
А если openssl свой уже имеется с ГОСТ? (правда он собран в отдельной папке отдельным файлом) К нему можно обращаться?

**Comment by Terciuss** [comment]
уточните пожалуйста, требуется ли расширение КриптоПро на сервере для подписания документов через api ?
